export const theme = {
  negro: '#0a0a0a',
  dorado: '#C9A84C',
  doradoClaro: '#E8C96D',
  doradoOscuro: '#9A7A2E',
  blanco: '#FFFFFF',
  grisClaro: '#F5F5F0',
  grisMedio: '#888888',
  error: '#E53935',
  exito: '#2E7D32',
}

export const estilos = {
  pantalla: {
    minHeight: '100vh',
    background: '#0a0a0a',
    color: '#FFFFFF',
    fontFamily: "'Georgia', serif",
    padding: '0 16px',
  },
  tarjeta: {
    background: '#1a1a1a',
    border: '1px solid #C9A84C',
    borderRadius: 16,
    padding: '24px 20px',
    marginBottom: 16,
  },
  input: {
    width: '100%',
    padding: '12px 14px',
    fontSize: 15,
    borderRadius: 10,
    border: '1px solid #C9A84C',
    background: '#1a1a1a',
    color: '#FFFFFF',
    boxSizing: 'border-box',
    outline: 'none',
  },
  botonDorado: {
    width: '100%',
    padding: '13px',
    fontSize: 16,
    borderRadius: 10,
    background: 'linear-gradient(135deg, #C9A84C, #E8C96D)',
    color: '#0a0a0a',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 700,
    letterSpacing: 1,
  },
  botonOscuro: {
    width: '100%',
    padding: '13px',
    fontSize: 15,
    borderRadius: 10,
    background: 'transparent',
    color: '#C9A84C',
    border: '1px solid #C9A84C',
    cursor: 'pointer',
    fontWeight: 600,
  },
}